# Kernel PCA - Classification

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.decomposition import KernelPCA

In [2]:
# Data Collection

raw_data = pd.read_csv("CKD.csv")
raw_data

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [3]:
df = raw_data

In [4]:
df = pd.get_dummies(df,dtype = int, drop_first=True)

In [5]:
# Input Output Split

indep_x = df.drop('classification_yes',axis = 1)
dep_y = df['classification_yes']

In [17]:
def split_scaler(indep_x,dep_y):
    x_train,x_test,y_train,y_test = train_test_split(indep_x,dep_y,test_size = 0.2, random_state=0)
    sc=StandardScaler()
    x_train = sc.fit_transform(x_train)
    x_test = sc.transform(x_test)
    return x_train,x_test,y_train,y_test

def cm_prediction(classifier,x_test,y_test):
    y_pred = classifier.predict(x_test)
    cm = confusion_matrix(y_test,y_pred)
    Accuracy = accuracy_score(y_test,y_pred)
    Report = classification_report(y_test,y_pred)
    return cm,Accuracy,Report

def logistic(x_train,y_train,x_test,y_test):
    classifier = LogisticRegression(random_state=0)
    classifier.fit(x_train,y_train)
    return cm_prediction(classifier,x_test,y_test)

def svm_linear(x_train,y_train,x_test,y_test):
    classifier = SVC(kernel='linear',random_state=0)
    classifier.fit(x_train,y_train)
    return cm_prediction(classifier,x_test,y_test)

def svm_nonlinear(x_train,y_train,x_test,y_test):
    classifier = SVC(kernel = 'rbf', random_state=0)
    classifier.fit(x_train,y_train)
    return cm_prediction(classifier,x_test,y_test)

def knn(x_train,y_train,x_test,y_test):
    classifier = KNeighborsClassifier(n_neighbors=5, metric = 'minkowski')
    classifier.fit(x_train,y_train)
    return cm_prediction(classifier,x_test,y_test)

def naive(x_train,y_train,x_test,y_test):   
    classifier = GaussianNB()
    classifier.fit(x_train,y_train)
    return cm_prediction(classifier,x_test,y_test)

def decision(x_train,y_train,x_test,y_test):
    classifier = DecisionTreeClassifier(criterion = 'entropy', random_state=0)
    classifier.fit(x_train,y_train)
    return cm_prediction(classifier,x_test,y_test)

def random(x_train,y_train,x_test,y_test):
    classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state=0)
    classifier.fit(x_train,y_train)
    return cm_prediction(classifier,x_test,y_test)

def KernelPCA_results(acclog,accsvml,accsvmnl,accknn,accnav,accdc,accrf):
    KernelPCAdataframe = pd.DataFrame(index = ['Logistic', 'SVM', 'Decision', 'Random'], columns = ['Logistic', 'SVM_l', 'SVM_nl', 'KNN',
                                                                                              'Naive','Decision','Random'])
    for index in KernelPCAdataframe.index:
        KernelPCAdataframe['Logistic'][index] = acclog
        KernelPCAdataframe['SVM_l'][index] = accsvml
        KernelPCAdataframe['SVM_nl'][index] = accsvmnl
        KernelPCAdataframe['KNN'][index] = accknn
        KernelPCAdataframe['Naive'][index] = accnav
        KernelPCAdataframe['Decision'][index] = accdc
        KernelPCAdataframe['Random'][index] = accrf
    return KernelPCAdataframe

In [18]:
acclog = []
accsvml = []
accsvmnl = []
accknn = []
accnav = []
accdc = []
accrf = []

In [19]:
# Train Test Split

x_train, x_test, y_train, y_test = split_scaler(indep_x,dep_y)

In [58]:
# Kernel PCA Model Creation

KPCA = KernelPCA(n_components = 1, kernel ='linear')
x_train_kpca = KPCA.fit_transform(x_train)
x_test_kpca = KPCA.transform(x_test)

In [54]:
# Calculate accuracies for each classifier

cm, Accuracy, Report = logistic(x_train_kpca,y_train,x_test_kpca,y_test)
acclog.append(Accuracy)

cm, Accuracy, Report = svm_linear(x_train_kpca,y_train,x_test_kpca,y_test)
accsvml.append(Accuracy)

cm, Accuracy, Report = svm_nonlinear(x_train_kpca,y_train,x_test_kpca,y_test)
accsvmnl.append(Accuracy)

cm, Accuracy, Report = knn(x_train_kpca,y_train,x_test_kpca,y_test)
accknn.append(Accuracy)

cm, Accuracy, Report = naive(x_train_kpca,y_train,x_test_kpca,y_test)
accnav.append(Accuracy)

cm, Accuracy, Report = decision(x_train_kpca,y_train,x_test_kpca,y_test)
accdc.append(Accuracy)

cm, Accuracy, Report = random(x_train_kpca,y_train,x_test_kpca,y_test)
accrf.append(Accuracy)

result = KernelPCA_results(acclog[0],accsvml[0],accsvmnl[0],accknn[0],accnav[0],accdc[0],accrf[0])

C:\Users\priya\AppData\Local\Temp\ipykernel_17772\2847197109.py:54: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  KernelPCAdataframe['Logistic'][index] = acclog
C:\Users\priya\AppData\Local\Temp\ipykernel_17772\2847197109.py:55: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  KernelPCAdataframe['SVM_l'][index] = accsvml
C:\Users\priya\AppData\Local\Temp\ipykernel_17772\2847197109.py:56: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  KernelPCAdataframe['SVM_nl'][index] = accsvmnl
C:\Users\priya\AppData\Local\Temp\ipykernel_17772\2847197109.py:57: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  KernelPCAdataframe['KNN'][index] = accknn
C:\Users\priya\AppData\Local\Temp\ipykernel_17772\2847197109.py:58: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  KernelPCAdataframe['Naive'][index] = accnav
C:\Users\priya\AppData\Local\Temp\ipykernel_17772\2847197109.py:59: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  KernelPCAdataframe['Decision'][index] = accdc
C:\Users\priya\AppData\Local\Temp\ipykernel_17772\2847197109.py:60: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  KernelPCAdataframe['Random'][index] = accrf

In [46]:
result
#2

         Logistic   SVM_l SVM_nl  KNN Naive Decision Random
Logistic   0.9875  0.9875    1.0  1.0   1.0      1.0    1.0
SVM        0.9875  0.9875    1.0  1.0   1.0      1.0    1.0
Decision   0.9875  0.9875    1.0  1.0   1.0      1.0    1.0
Random     0.9875  0.9875    1.0  1.0   1.0      1.0    1.0

In [49]:
result
#3

         Logistic   SVM_l SVM_nl  KNN Naive Decision Random
Logistic   0.9875  0.9875    1.0  1.0   1.0      1.0    1.0
SVM        0.9875  0.9875    1.0  1.0   1.0      1.0    1.0
Decision   0.9875  0.9875    1.0  1.0   1.0      1.0    1.0
Random     0.9875  0.9875    1.0  1.0   1.0      1.0    1.0

In [52]:
result
#4

         Logistic   SVM_l SVM_nl  KNN Naive Decision Random
Logistic   0.9875  0.9875    1.0  1.0   1.0      1.0    1.0
SVM        0.9875  0.9875    1.0  1.0   1.0      1.0    1.0
Decision   0.9875  0.9875    1.0  1.0   1.0      1.0    1.0
Random     0.9875  0.9875    1.0  1.0   1.0      1.0    1.0

In [55]:
result
#1

         Logistic   SVM_l SVM_nl  KNN Naive Decision Random
Logistic   0.9875  0.9875    1.0  1.0   1.0      1.0    1.0
SVM        0.9875  0.9875    1.0  1.0   1.0      1.0    1.0
Decision   0.9875  0.9875    1.0  1.0   1.0      1.0    1.0
Random     0.9875  0.9875    1.0  1.0   1.0      1.0    1.0